spring.application.name=application-cours-ligne

spring.datasource.url=jdbc:mysql://localhost:3306/cours-ligne

spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
